# Generated by Django 6.1.1 on 2026-09-04 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bl', models.CharField(max_length=50, unique=True, verbose_name='Numéro BL')),
                ('date_bl', models.DateField(verbose_name='Date BL')),
                ('nb_palettes_total', models.IntegerField(blank=True, null=True, verbose_name='Nb palettes total')),
                ('poids_brut', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids brut')),
                ('fichier_scan', models.FileField(blank=True, max_length=255, null=True, upload_to='scans/bl/', verbose_name='Fichier scan')),
            ],
            options={
                'verbose_name': 'Bon de livraison',
                'verbose_name_plural': 'Bons de livraison',
                'db_table': 'bon_livraison',
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mouvement', models.DateField(verbose_name='Date mouvement')),
                ('type_mouvement', models.CharField(choices=[('RECEPTION', 'RECEPTION'), ('EXPORT', 'EXPORT')], max_length=10, verbose_name='Type mouvement')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('nb_palettes', models.IntegerField(blank=True, null=True, verbose_name='Nb palettes')),
                ('batch', models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
                'db_table': 'mouvement',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_pn', models.CharField(max_length=50, unique=True, verbose_name='Code PN')),
                ('designation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Désignation')),
            ],
            options={
                'verbose_name': 'Référence',
                'verbose_name_plural': 'Références',
                'db_table': 'reference',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code site')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du site')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='BonLivraisonMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraison_mouvements', to='stock.bonlivraison', verbose_name='Bon de livraison')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraison_mouvements', to='stock.mouvement', verbose_name='Mouvement')),
            ],
            options={
                'verbose_name': 'Liaison Bon de livraison - Mouvement',
                'verbose_name_plural': 'Liaisons Bons de livraison - Mouvements',
                'db_table': 'bon_livraison_mouvement',
            },
        ),
        migrations.AddField(
            model_name='mouvement',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.reference', verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.site', verbose_name='Site'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro de facture')),
                ('date_facture', models.DateField(verbose_name='Date de facture')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant')),
                ('fichier_scan', models.FileField(blank=True, max_length=255, null=True, upload_to='scans/factures/', verbose_name='Fichier scan')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='stock.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'facture',
            },
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_livraison', to='stock.site', verbose_name='Site'),
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_trajet', models.DateField(verbose_name='Date trajet')),
                ('remarque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarque')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='stock.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'db_table': 'trajet',
            },
        ),
        migrations.CreateModel(
            name='RapprochementFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('OK', 'OK'), ('ECART', 'ECART')], default='OK', max_length=20, verbose_name='Statut')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements', to='stock.facture', verbose_name='Facture')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements', to='stock.trajet', verbose_name='Trajet')),
            ],
            options={
                'verbose_name': 'Rapprochement Facture - Trajet',
                'verbose_name_plural': 'Rapprochements Factures - Trajets',
                'db_table': 'rapprochement_facture',
            },
        ),
        migrations.CreateModel(
            name='TrajetMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_transportee', models.IntegerField(verbose_name='Quantité transportée')),
                ('nb_palettes_transportees', models.IntegerField(blank=True, null=True, verbose_name='Nb palettes transportées')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajet_mouvements', to='stock.mouvement', verbose_name='Mouvement')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajet_mouvements', to='stock.trajet', verbose_name='Trajet')),
            ],
            options={
                'verbose_name': 'Liaison Trajet - Mouvement',
                'verbose_name_plural': 'Liaisons Trajets - Mouvements',
                'db_table': 'trajet_mouvement',
            },
        ),
    ]
