# Generated by Django 6.1.1 on 2026-09-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bonlivraisonmouvement',
            unique_together={('bon_livraison', 'mouvement')},
        ),
        migrations.AlterUniqueTogether(
            name='trajetmouvement',
            unique_together={('trajet', 'mouvement')},
        ),
    ]
