# Generated by Django 6.1.1 on 2026-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_bonlivraisonmouvement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='nb_trajets_factures',
            field=models.IntegerField(blank=True, help_text='Nombre de trajets déclarés par le transporteur sur cette facture', null=True, verbose_name='Nb trajets déclarés'),
        ),
    ]
